/******************************************************************************

Welcome to GDB Online.
GDB online is an online compiler and debugger tool for C, C++, Python, PHP, Ruby, 
C#, VB, Perl, Swift, Prolog, Javascript, Pascal, HTML, CSS, JS
Code, Compile, Run and Debug online from anywhere in world.

*******************************************************************************/
#include <stdio.h>

int main()
{
    printf("Hello World \n");
    bool tf=false;
    int t=32,u=20,v=18;
    char r='r', q='q', h=32;
    
    
    printf("tf=%i \n");
    printf("t=%d u=%d v=%d \n",t,u,v);
    printf("r=%c q=%c h=%cd \n",r,q,h);
    

    return 0;
}
